import json
import os

path = r'C:\experiment\labquake_explorer_re\export h5\2D_Summary_Plots.ipynb'
with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

cells = nb['cells']

# =========================================================
# Cell index 3: plot_metric
# =========================================================
new_plot_metric = [
    "# ========= 3. 繪製圖表函數 (Plotting Function) =========\n",
    "\n",
    "def plot_metric(target_metric, title, ylabel):\n",
    "    data_to_plot = process_data(target_metric)\n",
    "    if not data_to_plot:\n",
    "        print(f\"找不到 {target_metric} 的資料\")\n",
    "        return\n",
    "\n",
    "    # 離散 colormap：從 Set2 原始 8 色中按序取前 n 個\n",
    "    group_vals = [item['group_val'] for item in data_to_plot]\n",
    "    n = len(group_vals)\n",
    "    cmap_full = plt.get_cmap('Set2')  # 原始 8 色\n",
    "    colors = [cmap_full(i / 8) for i in range(n)]  # 按序取前 n 個\n",
    "    val_to_idx = {v: i for i, v in enumerate(group_vals)}\n",
    "\n",
    "    # 用於 colorbar 的 ScalarMappable\n",
    "    from matplotlib.colors import ListedColormap, BoundaryNorm\n",
    "    cmap_cb = ListedColormap(colors)\n",
    "    bounds = [i - 0.5 for i in range(n)] + [n - 0.5]\n",
    "    norm_cb = BoundaryNorm(bounds, cmap_cb.N)\n",
    "    sm = plt.cm.ScalarMappable(cmap=cmap_cb, norm=norm_cb)\n",
    "    sm.set_array([])\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "\n",
    "    all_sigmas = []\n",
    "    texts_to_draw = []\n",
    "    for item in data_to_plot:\n",
    "        stats = item['stats']\n",
    "        sigmas = stats['sigma'].values\n",
    "        medians = stats['median'].values\n",
    "        yerr_lower = medians - stats['q1'].values\n",
    "        yerr_upper = stats['q3'].values - medians\n",
    "        color = colors[val_to_idx[item['group_val']]]\n",
    "\n",
    "        all_sigmas.extend(sigmas)\n",
    "\n",
    "        ax.errorbar(\n",
    "            sigmas, medians,\n",
    "            yerr=[yerr_lower, yerr_upper],\n",
    "            fmt=item['marker'], color=color,\n",
    "            markersize=10, capsize=5,\n",
    "            markerfacecolor='none', markeredgewidth=2,\n",
    "            elinewidth=1.5, alpha=0.8, zorder=3\n",
    "        )\n",
    "\n",
    "        # Add trend line\n",
    "        if target_metric == 'delta_tau' and len(sigmas) > 2:\n",
    "            coefs = np.polyfit(sigmas, medians, 2)\n",
    "            x_line = np.linspace(sigmas.min(), sigmas.max(), 50)\n",
    "            y_line = np.polyval(coefs, x_line)\n",
    "            ax.plot(x_line, y_line, color=color, linestyle='--', linewidth=1.5, alpha=0.6, zorder=2)\n",
    "        elif len(sigmas) > 1:\n",
    "            slope, intercept = np.polyfit(sigmas, medians, 1)\n",
    "            x_line = np.array([sigmas.min(), sigmas.max()])\n",
    "            y_line = slope * x_line + intercept\n",
    "            ax.plot(x_line, y_line, color=color, linestyle='--', linewidth=1.5, alpha=0.6, zorder=2)\n",
    "            texts_to_draw.append({\n",
    "                'x': x_line[-1] + 0.5,\n",
    "                'y': y_line[-1],\n",
    "                'text': f' m={slope:.3g}',\n",
    "                'color': color\n",
    "            })\n",
    "\n",
    "    ax.set_xlabel(r'Normal Stress $\\sigma$ [MPa]', fontsize=12)\n",
    "    ax.set_ylabel(ylabel, fontsize=12)\n",
    "    ax.set_title(title, fontsize=14)\n",
    "    ax.grid(True, alpha=0.6)\n",
    "    ax.set_xlim(xlim_min, xlim_max)\n",
    "\n",
    "    if all_sigmas:\n",
    "        ax.set_xticks(np.unique(all_sigmas))\n",
    "\n",
    "    # 離散 colorbar\n",
    "    cbar = fig.colorbar(sm, ax=ax, ticks=list(range(n)))\n",
    "    cbar.set_label('Seismogenic Zone Size [cm]', fontsize=11)\n",
    "    cbar.ax.set_yticklabels([item['group'] for item in data_to_plot])\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
]
cells[3]['source'] = new_plot_metric

# =========================================================
# Cell index 4: plot_metric_by_group
# =========================================================
new_plot_by_group = [
    "# ========= 4. 以群組為 X 軸的繪圖函數 (Group X-Axis Plotting Function) =========\n",
    "\n",
    "# Sigma -> 標記 映射（顏色改由 colormap 決定）\n",
    "SIGMA_MARKER = {\n",
    "    1.0: \"s\",\n",
    "    2.0: \"^\",\n",
    "    4.0: \"D\",\n",
    "    8.0: \"d\",\n",
    "}\n",
    "\n",
    "\n",
    "def plot_metric_by_group(target_metric, title, ylabel):\n",
    "    \"\"\"以實驗群組為 X 軸（順序與 experiments 設定相同），不同 sigma 為系列繪圖。\"\"\"\n",
    "    group_order = [exp[\"group\"] for exp in experiments]\n",
    "    group_xval  = {g: i for i, g in enumerate(group_order)}\n",
    "\n",
    "    data_to_plot = process_data(target_metric)\n",
    "    if not data_to_plot:\n",
    "        print(f\"找不到 {target_metric} 欄位\")\n",
    "        return\n",
    "\n",
    "    # 收集所有出現的 sigma 值\n",
    "    all_sigmas_set = set()\n",
    "    for item in data_to_plot:\n",
    "        all_sigmas_set.update(item[\"stats\"][\"sigma\"].values)\n",
    "    unique_sigmas = sorted(all_sigmas_set)\n",
    "\n",
    "    # 離散 colormap：從 Set2 原始 8 色中按序取前 n 個\n",
    "    n = len(unique_sigmas)\n",
    "    cmap_full = plt.get_cmap('Set2')  # 原始 8 色\n",
    "    colors = [cmap_full(i / 8) for i in range(n)]  # 按序取前 n 個\n",
    "    sigma_to_idx = {s: i for i, s in enumerate(unique_sigmas)}\n",
    "\n",
    "    # 用於 colorbar 的 ScalarMappable\n",
    "    from matplotlib.colors import ListedColormap, BoundaryNorm\n",
    "    cmap_cb = ListedColormap(colors)\n",
    "    bounds = [i - 0.5 for i in range(n)] + [n - 0.5]\n",
    "    norm_cb = BoundaryNorm(bounds, cmap_cb.N)\n",
    "    sm = plt.cm.ScalarMappable(cmap=cmap_cb, norm=norm_cb)\n",
    "    sm.set_array([])\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "    texts_to_draw = []\n",
    "\n",
    "    for sigma in unique_sigmas:\n",
    "        x_vals, y_vals, yerr_lo, yerr_hi = [], [], [], []\n",
    "\n",
    "        for item in data_to_plot:\n",
    "            group = item[\"group\"]\n",
    "            if group not in group_xval:\n",
    "                continue\n",
    "            stats = item[\"stats\"]\n",
    "            row = stats[stats[\"sigma\"] == sigma]\n",
    "            if row.empty:\n",
    "                continue\n",
    "            x_vals.append(group_xval[group])\n",
    "            med = row[\"median\"].values[0]\n",
    "            q1  = row[\"q1\"].values[0]\n",
    "            q3  = row[\"q3\"].values[0]\n",
    "            y_vals.append(med)\n",
    "            yerr_lo.append(med - q1)\n",
    "            yerr_hi.append(q3 - med)\n",
    "\n",
    "        if not x_vals:\n",
    "            continue\n",
    "\n",
    "        x_arr = np.array(x_vals)\n",
    "        y_arr = np.array(y_vals)\n",
    "        color = colors[sigma_to_idx[sigma]]\n",
    "        marker = SIGMA_MARKER.get(sigma, \"o\")\n",
    "\n",
    "        ax.errorbar(\n",
    "            x_arr, y_arr,\n",
    "            yerr=[np.array(yerr_lo), np.array(yerr_hi)],\n",
    "            fmt=marker, color=color,\n",
    "            markersize=10, capsize=5,\n",
    "            markerfacecolor=\"none\", markeredgewidth=2,\n",
    "            elinewidth=1.5, alpha=0.8, zorder=3\n",
    "        )\n",
    "\n",
    "        # 趨勢線\n",
    "        if target_metric == 'delta_tau' and len(x_arr) > 2:\n",
    "            coefs = np.polyfit(x_arr, y_arr, 2)\n",
    "            x_line = np.linspace(x_arr.min(), x_arr.max(), 50)\n",
    "            y_line = np.polyval(coefs, x_line)\n",
    "            ax.plot(x_line, y_line, color=color, linestyle=\"--\", linewidth=1.5, alpha=0.6, zorder=2)\n",
    "        elif len(x_arr) > 1:\n",
    "            slope, intercept = np.polyfit(x_arr, y_arr, 1)\n",
    "            x_line = np.array([x_arr.min(), x_arr.max()])\n",
    "            y_line = slope * x_line + intercept\n",
    "            ax.plot(x_line, y_line, color=color, linestyle=\"--\", linewidth=1.5, alpha=0.6, zorder=2)\n",
    "            texts_to_draw.append({\n",
    "                \"x\": x_line[-1] + 0.1,\n",
    "                \"y\": y_line[-1],\n",
    "                \"text\": f\" m={slope:.3g}\",\n",
    "                \"color\": color\n",
    "            })\n",
    "\n",
    "    ax.set_xlabel(\"Seismogenic Zone Size\", fontsize=12)\n",
    "    ax.set_ylabel(ylabel, fontsize=12)\n",
    "    ax.set_title(title, fontsize=14)\n",
    "    ax.set_xlim(-0.5, len(group_order) - 0.5)\n",
    "    ax.set_xticks(range(len(group_order)))\n",
    "    ax.set_xticklabels(group_order)\n",
    "    ax.grid(True, alpha=0.6)\n",
    "\n",
    "    # 離散 colorbar\n",
    "    cbar = fig.colorbar(sm, ax=ax, ticks=list(range(n)))\n",
    "    cbar.set_label(r'Normal Stress $\\sigma$ [MPa]', fontsize=11)\n",
    "    cbar.ax.set_yticklabels([f'{s:.0f} MPa' for s in unique_sigmas])\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
]
cells[4]['source'] = new_plot_by_group

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("Done. Stress drop uses 2nd degree polynomial now.")
